sudo: required
services:
  - docker

before_install:
  - docker build -t dbarbuscio/react-test -f Dockerfile.dev .

script:
  - docker run dbarbuscio/react-test yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: react-testing
  env: "ReactTesting-env"
  bucket_name: "elasticbeanstalk-us-east-2-215656452330"
  bucket_path: "react-testing"
  on:
    branch: master
  access_key_id: $AWS_KEY
  secret_acccess_key:
    secure: "$AWS_SECRET"
